<?php

declare(strict_types=1);

namespace Isapp\ImageTools\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

use function app;
use function base_path;

/**
 * Artisan command to remove all files generated by ImageTools and
 * delete the manifest file. The command uses the current manifest
 * to determine which files to delete and does not scan the disk.
 */
class ClearGeneratedImagesCommand extends Command
{
    protected $signature = 'imagetools:clear';
    protected $description = 'Clear generated ImageTools files and remove the manifest.';

    public function handle(): int
    {
        // Read package configuration (disk, manifest path, scan paths).
        $config = app('config')->get('image-tools');

        // Resolve absolute path to the manifest file.
        $defaultManifest = base_path($config['manifest_path']);
        // Nothing to clear if the manifest is missing.
        if (! File::exists($defaultManifest)) {
            $this->warn('Manifest file [' . $config['manifest_path'] . '] is not exists');

            return self::SUCCESS;
        }

        // Load current manifest (array of [path, disk] entries).
        $manifest = require $defaultManifest;

        // Remove the manifest first to avoid stale reads.
        File::delete($defaultManifest);

        // Delete each generated file using its original disk.
        foreach ($manifest as $file) {
            Storage::disk($file['disk'])->delete($file['path']);
        }

        return self::SUCCESS;
    }
}
